### ISSUE TITLE
KTor RunBlocking

### ISSUE THREAD

**Issue by cody1024d** [bootstraponline/run_blocking#1]
@bootstraponline I apologize for posting on a repo that hasn't been updated in a while, but I have a very similar use-case.  I am using ktor to write a framework to be used within the context of UI Tests of other projects.  Thus, I need the network calls to happen synchronously.  I haven't been able to get this working, even with the code you have shared above.

Were you ever able to resolve this?

Have you used this recently?  As it doesn't seem to be working for me on the latest version of ktor (1.2.5)

**Comment by bootstraponline** [comment]
I'll take a look. If I remember correctly it worked on Android and had problems on iOS. The Kotlin Slack is where I discussed solutions.

**Comment by bootstraponline** [comment]
I pushed a fix. CommonTest passes again with updated deps:
https://github.com/bootstraponline/run_blocking/commit/f16e89b35915e6e6c9bc67dd3d7fa2534089a191

iOS is blocked on: https://github.com/Kotlin/kotlinx.coroutines/issues/462

**Comment by cody1024d** [comment]
@bootstraponline Ok yeah, that's what I was afraid of.  

Did you ever solve your use-case?  

Move to calling NSURLSession yourself or something? I would assume that would work, as there wouldn't be any coroutines involved then (and since I need it done synchronously anyway...)

**Comment by bootstraponline** [comment]
I ended up going back to Kotlin and Swift because Kotlin multiplatform is not mature on iOS. It wasn't worth the increase in complexity. There are too many bugs that have no timeline for being fixed.

I think if you ask on the Kotlin Slack, someone must have figured out a work around. My guess is if you avoid coroutines it's probably possible to get something working.

**Comment by cody1024d** [comment]
Sounds good.  Thanks @bootstraponline!

**Comment by bootstraponline** [comment]
I updated the example to use native `runBlocking` on iOS. The code compiles into `run_blocking.framework` and the health check can be invoked from Swift:

```swift
import run_blocking

CommonKt.healthCheck();
```

The problem is iOS appears to hang indefinitely on `kotlinx.coroutines.runBlocking`.
